jwt:
   time: 90000
   ret: hello-world1234
psoco:
   name: 3기기여미
   count: 200
test:
   datasource:
      url: jdbc:mysql://localhost:3306/insta?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
